import './globals.css'
import Navigation from "./components/navigation";

import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })



export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html>
      <body className={inter.className}>
        <Navigation />
        {children}
        
      </body>
    </html>
  )
}
